### ISSUE TITLE
Minimal project setup

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-oce#1]
Create the minimal project setup:

- gradle multip-project build (gradle 5.0 would be great if this is out)
  - since we would have only one project not sure if we need any crazy dependency strategy
  - keep `jmh`, `jococo`, etc
- new project for the agent (`inspectit-oce-agent`?)
  - target the `1.8` for now
  - create the agent entry point, implement both `premain` and `agentmain` (simple sysout) -> see https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/package-summary.html
  - create proper manifest in the build
  - copy from the old the utility to check if dependencies are in `1.8` target
  - what else we would need right away from the old project?
- `.gitignore` that works with intellij (at best copy what's generated from Spring initz, I always found these to be good)
- IntelliJ setup
  - save actions plugin, export configuration -> automatic formatting and import org when saved (Ivan can share configuration)
- create `CONTRIBUTE.MD` and share any needed development environment setup

Confirm:
- agent can be added by `-javaagent` (test versions 8 & 11) 
- agent can be attached to any already running JVM with utility like https://github.com/apangin/jattach (test versions 8 & 11)

**Comment by mariusoe** [comment]
> since we would have only one project not sure if we need any crazy dependency strategy
I think we can (and should) keep this simple. I see no benefit if we create a complicated and fancy dependency strategy
