### ISSUE TITLE
Add special instrumentation for OSGi-style classloaders

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-oce#116]
Our instrumentation assumes that our bootstrap classes are accessible from every application classloader.
This is not always the case, e.g. in OSGi. In this cases our classes would most likely result in the application terminating with NoClassDefErrors.

We can prevent this by checkling if our bootstrap classes are reachable from the target classloader before performing an instrumentation. In case we discover that our bootstrap classes are not reachable we could add a classlaoder delegation similar to the old inspectit.

**Comment by mariusoe** [comment]
Added to M3
