### ISSUE TITLE
Extending configuration to enable an annotation based target selection

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-oce#59]
Should support:

* interface
* super-class
* class-annotation
* method-annotation
* method parameters (by default all methods with given name)
* modifiers (only public by default? at least private should be not instrumented by default)

Please separate the class name, interface and super-class, we should allow configs that define all 3 and not like now only one FQN.

Nice to have (can be separated into further tickets and moved to another milestone):
* wild-card (this is great, but we need to be careful here for what we want a wild-card to be possible)
  * don't allow `*` only
* when the instrumenting by interface, instrument only methods available in that interface
* when the instrumenting by super-class, instrument only methods available in that super-class

**Comment by mariusoe** [comment]
In #58, the configuration is basically covering all the points mentioned in this ticket except annotation based configuration, thus, it is renamed.
