### ISSUE TITLE
Strategy to propagate the context up the stack trace

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-oce#74]
Use case: sometimes information related to the user request is not available in the entry point (f.e. business transaction is recognized somewhere in the impl flow). We need a way to propagate such information up so when metric is recorded we would have these tags also available.

* data providers could opt to propagate up
* propagation is done in the inspectIT specific GRPC context key at the exit
* overwrite config option can be added to know what to do if key already available (f.e. two methods report the BT)

**Comment by JonasKunz** [comment]
I think we have to limit the up-propagation to synchronous calls (= Java method calls). When doing the up-propagation across thread borders we could run into race-conditions and indeterminism

**Comment by JonasKunz** [comment]
Fixed via #109 and #111.
