### ISSUE TITLE
User defined exclude packages/classes

### ISSUE THREAD

**Issue by ivansenic** [inspectIT/inspectit-oce#79]
The user should have possibility to exclude classes by package or FQN.

**Comment by JonasKunz** [comment]
We discovered more issues with the intelliJ agent in combination with the thread context propagation: when the context to propagate is not empty, it causes the entire application to crash for some reason. It is not possible to catch any exception or debug here as something gets messed up in the intelliJ agent.
For this reason we include "com.intelliJ" as default with the user excludes.
