### ISSUE TITLE
Upload test reports after failures on TravisCI

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-oce#80]
Currently some test fail occasionally as they assert that no errors or logs are generated by the agent.
However, travis does currently not show the stdout of the executed tests.

Therefore we either need to make travis output the test logs to the build log or let travis upload the report to the S3 in case of a test failure.

**Comment by mariusoe** [comment]
Test-reports will be automatically uploaded to https://transfer.sh/ where they will be publy available and stored for 14 days.
The link where the test-reports can be downloaded is printed out by TravisCI.
